### ISSUE TITLE
Can't post install extra apps

### ISSUE THREAD

**Issue by j33n** [fusionpbx/fusionpbx-apps#1]
Hello. Can anybody help me with post instalation new extra apps in FusionPBX using .deb packages.
I find only one instruction for post instalation extra packages - http://wiki.fusionpbx.com/index.php?title=Debian_Fusionpbx_Pkg_or_Source_Install#Post_Install_Of_Optional.2FExtra_Modules.2FApps_for_Fusionpbx_Web_Gui
This manual say:

  RTPM: (Html5 Sip Soft Phone)
  apt-get -y --force-yes install fusionpbx-app-sipml5 freeswitch-mod-rtmp

but wthen I try, Debian print: 

  spark@sip:~$ sudo apt-get -y --force-yes install fusionpbx-app-sipml5 freeswitch-mod-rtmp
  Reading package lists... Done
  Building dependency tree
  Reading state information... Done
  E: Unable to locate package fusionpbx-app-sipml5
  E: Unable to locate package freeswitch-mod-rtmp

After I try find repo for FusionPBX and find in install script for Debian - https://github.com/fusionpbx/fusionpbx-scripts/blob/master/install/Debian/FusionPbx-Debian-Optional-Pkgs-or-Source-Install.sh

  echo "installing wheezy release repo"
  cat > "/etc/apt/sources.list.d/freeswitch.list" <<DELIM
  deb http://repo.fusionpbx.com/freeswitch/release/debian/ wheezy main
  #deb http://files.freeswitch.org/repo/deb/debian/ wheezy main

When I try resolve repo.fusionpbx.com, I get error:

  spark@sip:~$ ping repo.fusionpbx.com
  ping: unknown host repo.fusionpbx.com

And now I can understand where I must search this packeges.
Install extra app with simply download app from git, add to webserver and update FusionPBX from web don't help me. I can't find this app in my FusionPBX web.

My version of Fusion:
![image](https://cloud.githubusercontent.com/assets/9937165/9354795/094ce124-467c-11e5-81e5-d060ff75b4fc.png)

**Comment by markjcrane** [comment]
The Debian package is not being maintained by anyone and is not supported. The person hosting repo.fusionpbx.com shutdown that server and the original author did what I thought he would do eventually... he abandoned it.
