### ISSUE TITLE
In invoices app, the invoices.php has incorrect href link

### ISSUE THREAD

**Issue by nexusxo** [fusionpbx/fusionpbx-apps#37]
Hello,

On Line 158 in invoices.php, it has the href for deleting invoices incorrect, so it shows error "file not found". The "invoices_delete.php" needs to be changed to "invoice_delete.php" (remove the the s on invoices).

Current Line : echo <a href='**_invoices_**_delete.php?contact_uuid=".$row['contact_uuid']."&id=".$row['invoice_uuid'].$back."' alt='".$text['button-delete']."' onclick=\"return confirm('".$text['confirm-delete']."')\">$v_link_label_delete</a>";

Proposed Change: echo <a href='**_invoice_**_delete.php?contact_uuid=".$row['contact_uuid']."&id=".$row['invoice_uuid'].$back."' alt='".$text['button-delete']."' onclick=\"return confirm('".$text['confirm-delete']."')\">$v_link_label_delete</a>";

Thank you!
Matt

Note: I tried to submit a proposed change, but it would not let me submit it.

**Comment by markjcrane** [comment]
Thanks for reporting this and the fix. I removed the 's' as recommended.
