### ISSUE TITLE
bulk account settings

### ISSUE THREAD

**Issue by fitreklam** [fusionpbx/fusionpbx-apps#55]
Hello there

Do you have any of the following faults?

Fatal error: Call to undefined method database::select() in /var/www/fusionpbx/app/bulk_account_settings/bulk_account_settings_extensions.php on line 114

Fatal error: Call to undefined method database::select() in /var/www/fusionpbx/app/bulk_account_settings/bulk_account_settings_devices.php on line 120

Fatal error: Call to undefined method database::select() in /var/www/fusionpbx/app/bulk_account_settings/bulk_account_settings_users.php on line 105

Fatal error: Call to undefined method database::select() in /var/www/fusionpbx/app/bulk_account_settings/bulk_account_settings_voicemails.php on line 113

**Comment by markjcrane** [comment]
Its built for the master branch at the moment.

**Comment by ruslanguns** [comment]
May I ask you something? How stable is the Master branch, ready for production?

**Comment by markjcrane** [comment]
Its kept pretty stable however when its ready for release we will release it as version 4.4.
