### ISSUE TITLE
how does webrtc work

### ISSUE THREAD

**Issue by nick950222** [fusionpbx/fusionpbx-apps#65]
I installed webrtc and upgraded the menu and the verto is on and everything is functional 
But how does it work? There is no button to select a video feed , no button to set up a video conference and no nothing ! Can anybody tell me how to use it?

**Comment by nick950222** [comment]
@ @markjcrane @crazyquark @thefinn93

**Comment by thefinn93** [comment]
Why are you asking me this?

**Comment by markjcrane** [comment]
FusionPBX follows FreeSWITCH for this topic go buy the lastest FreeSWITCH as it describes how to do it.
