### ISSUE TITLE
What is the difference between fusionpbx-apps and fusionpbx with built in apps?

### ISSUE THREAD

**Issue by shadowym** [fusionpbx/fusionpbx-apps#9]
I am trying to figure out what fusionpbx-apps are compared to the apps already included with fusionpbx.  Can anyone enlighten me?

They are not the same as far as I can tell.  Not sure how to install them either and have yet to find instructions.

**Comment by markjcrane** [comment]
Ones in the main fusionpbx directory  are default.  The fusionpbx-apps are
optional some are old and some are new. To download them you get the files
with git and put them in the fusionpbx/app directory. We will build an easy
install tool in the future.

Mark

**Comment by devravi** [comment]
Hi Mark,
When i put them under fusionpbx/app, it doesn't show in software? any other configuration needed?
(I put invoices app in fusionpbx/app directory)

**Comment by powerpbx** [comment]
Without an installer that does it for you, I believe you have to add them to the menu manually.

Advanced > Menu Manager

**Comment by moteus** [comment]
May be just Upgrade -> Schema/Default/Menu.
I never try but I think it should work.

**Comment by devravi** [comment]
Hi Moteus,
Upgrade -> Schema/Default/Menu, not worked I added menu manually from 
Advance -> Menu manager, I added it under Apps menu, but when i click on Invoices it shows 
white page with "No input file specified." 

Also tried executing:
     Upgrade -> App Defaults
     Upgrade -> Menu Defaults 

Didn't helped? Is there any document for installation?

**Comment by markjcrane** [comment]
The right way to do it is add the source code into fusionpbx/app directory so you would have fusionpbx/app/invoices. Make the web server the owner of the files.

Advanced -> Upgrade
Schema
Menu Defaults
Permission Defaults 

Run these one at a time. Then logout and back in. 

Menu -> App -> Invoices.

I have it installed and working on my server.

**Comment by devravi** [comment]
Hello Mr. Owner Markjcrane :-),
Thank you for the steps,
This step helped me web server the owner of the files.
Thanks you.

**Comment by voiphoenix** [comment]
Hello Mr. Markjcrane
I did exactly what you recommended to install the app Invoices but the database for the invoices never got created. Please, can you tell me what to do ?

**Comment by voiphoenix** [comment]
I fixed.
